In [1]:
import numpy as np

# Population
* The grop that er are interested in studing
* Denoted as (N)

In [2]:
N = np.random.randint(60, size=(1000))
print("Generate 1000 random numbers between 1-60")

Generate 1000 random numbers between 1-60


# Sample
* It's a sub-set of the Population
* Denoted as (n)

In [3]:
# n1 is sample 1 taken from Population (N)
n1 = np.random.choice(N, size=100)
n1

array([ 2, 48,  0,  0, 36, 53,  1, 16, 30, 39,  5, 21, 58, 42, 14, 34, 47,
       39, 22, 14, 58,  0,  4,  1, 25, 21, 47, 26, 53,  4,  3, 40,  5, 26,
       30,  5, 28, 37, 47, 21, 18, 43, 58, 23,  9, 57,  3, 48, 52, 42, 49,
       26, 22, 31, 55, 42, 11,  6, 39, 39, 16, 39, 27, 39, 54,  2, 29, 39,
       45,  4, 43, 29, 28, 37, 41, 11, 20, 22, 58, 11, 49, 41, 45, 51, 54,
       21, 18, 36, 47, 18, 24, 28, 37, 48, 55,  4, 50,  6, 55, 39])

# Sampling Techinique
* The goal of sampling is to create a simple that is representation of the entire population
1. Simple Random Sampling
2. Stratified Sampling
3. Systematic Sampling
4. Convenience Sampling

## 1) Simple Random Sampling
* When performing simple random sempling, every member of the population (N) has as equal chance of being selected for your sample (n)

In [4]:
# Example
n1 = np.random.choice(N, size=100)
n1

array([28, 38, 43, 27, 28, 10, 43, 34,  4, 28, 14, 30,  4, 18, 39, 17,  4,
       28, 42, 15,  4, 50, 22, 29, 15, 50, 12,  9, 20, 17, 41,  7, 23, 39,
       13, 53, 55,  7, 54, 50, 18, 35,  0, 29,  2, 10, 42, 13, 42, 57, 31,
       13, 33, 28, 25, 12, 51, 14, 11, 35, 27, 32, 37, 18,  1, 13, 52, 15,
        7, 18, 28, 20, 18, 11, 12, 39, 39, 45, 33, 47, 21, 53, 50, 24, 56,
       23,  4, 44, 43, 43,  8, 40, 39, 26, 49, 41, 24, 23, 42,  1])

## 2) Stratified Sampling
* It's creates the non-overlaping groups

In [5]:
n1 = N[:200]
n2 = N[200:400]
n3 = N[400:600]
n4 = N[600:800]
n5 = N[800:]
n1

array([21, 40,  4,  2, 21,  4, 40, 47, 29, 42, 53, 44,  4,  9, 27, 13, 31,
       55, 41, 52, 50, 40, 34, 25, 27,  3, 49, 29, 17, 30, 58, 59, 40, 48,
       40, 55, 29, 39, 59,  6, 47,  8, 19, 53, 41, 52, 56, 23, 29, 28, 39,
       50, 27, 32, 18, 28, 51, 58, 54, 40, 30,  5, 29, 46, 36, 59, 31, 16,
       28, 35, 10, 39, 51,  9, 26, 11,  0, 25, 21, 45, 15, 53, 15, 58, 55,
       52, 17, 39,  0, 17, 42, 51, 51, 46, 23,  7, 39, 14, 13, 22, 32, 21,
       45, 54, 58, 27,  7, 11, 42, 36, 27, 33, 22, 34,  8, 46, 30, 21, 35,
       40, 10, 10, 53,  8, 41,  9, 38, 24, 15, 19, 50,  9, 18, 10, 29, 15,
       13, 44, 46, 26,  4, 49, 18, 32, 25, 24, 38, 14, 52, 52, 53, 50, 42,
       37, 39, 41, 57, 48,  7, 54, 43, 27, 39,  7, 40, 19, 41, 11, 33, 34,
       25, 21, 50, 56, 50,  3, 21, 14, 31, 26, 32, 38, 35, 46,  2, 27, 22,
       26,  3, 47, 43,  5, 52, 56, 12, 18, 17, 31,  0, 14])

## Systematic sampling

In [6]:
# Taking first 100 odd-index values sample as n1
n1 = N[:200:2]
# Taking first 100 even-index values sample as n1
n2 = N[1:201:2]
n1

array([21,  4, 21, 40, 29, 53,  4, 27, 31, 41, 50, 34, 27, 49, 17, 58, 40,
       40, 29, 59, 47, 19, 41, 56, 29, 39, 27, 18, 51, 54, 30, 29, 36, 31,
       28, 10, 51, 26,  0, 21, 15, 15, 55, 17,  0, 42, 51, 23, 39, 13, 32,
       45, 58,  7, 42, 27, 22,  8, 30, 35, 10, 53, 41, 38, 15, 50, 18, 29,
       13, 46,  4, 18, 25, 38, 52, 53, 42, 39, 57,  7, 43, 39, 40, 41, 33,
       25, 50, 50, 21, 31, 32, 35,  2, 22,  3, 43, 52, 12, 17,  0])

## Convenience Sampling
* Voluntary Response Sampling